"""
Constants used in strategy tuning
"""

# Mathematical Constants
RISK_FREE_RATE = 0.05  # 5% annual
ANNUAL_TRADING_DAYS = 252
PERCENTAGE_MULTIPLIER = 100.0
SCORE_MIN = -1.0
SCORE_MAX = 1.0

# Time Horizons (days) - configurable via trading config where used
HORIZON_10D = 10
HORIZON_20D = 20
HORIZON_30D = 30
MARKET_CONDITION_WINDOW_DAYS = 20
MARKET_CONDITION_LOOKBACK_BUFFER = 10
DRAWDOWN_WINDOW_BEFORE = 5
DRAWDOWN_WINDOW_AFTER = 10
MONTH_DAYS_APPROX = 30
TOP_N_WORST_TRADES = 5
REPORT_SEPARATOR_WIDTH = 80
